### ISSUE TITLE
No configuration.

### ISSUE THREAD

**Issue by glennposadas** [DinoLeung/pomodoro#2]
Can't run
<img width="748" alt="Screen Shot 2021-10-10 at 9 36 54 PM" src="https://user-images.githubusercontent.com/12502679/136698089-b72a9eaa-2a45-4ab7-84b8-01332e5fbb4d.png">
.

**Comment by DinoLeung** [comment]
@glennposadas you should be able to run the web version by executing `flutter run -d chrome` from the project root.

**Comment by DinoLeung** [comment]
Closing this as it has no activites
